/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : RTC.c
**     Project     : TabataTimer4_2
**     Processor   : MKL26Z128VFT4
**     Component   : Init_SRTC
**     Version     : Component 01.005, Driver 01.05, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-10-29, 09:04, # CodeGen: 0
**     Abstract    :
**          This file implements the SRTC (RTC) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : RTC
**          Device                                         : RTC
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Oscillator settings                          : 
**              Oscillator state                           : Enabled
**              Oscillator 2pF load                        : Enabled
**              Oscillator 4pF load                        : Disabled
**              Oscillator 8pF load                        : Enabled
**              Oscillator 16pF load                       : Disabled
**              The 32kHz clock output                     : Enabled
**            Prescaler and compensation settings          : 
**              Time prescaler                             : 0
**              Compensation interval                      : 0
**              Compensation value                         : 0
**              Compensation time                          : STOP
**            Time settings                                : 
**              Time [s]                                   : 0
**              Alarm time [s]                             : 0
**            Access settings                              : 
**              User code write access                     : Disabled
**              Register lock (VBAT power domain)          : 
**                Lock register                            : Not locked
**                Status register                          : Not locked
**                Control register                         : Not locked
**                Time compensation register               : Not locked
**            Update mode                                  : Disabled only
**          Pins                                           : 
**            Square-wave output pin                       : Disabled
**            Wakeup pin                                   : Disabled
**          Interrupts                                     : 
**            RTC interrupt                                : 
**              Interrupt                                  : INT_RTC
**              Interrupt request                          : Disabled
**              Interrupt priority                         : 0 (Highest)
**              ISR Name                                   : RTCInterrrupt
**              Alarm interrupt                            : Enabled
**              Time overflow interrupt                    : Enabled
**              Time invalid interrupt                     : Enabled
**            RTC seconds interrupt                        : 
**              Interrupt                                  : INT_RTC_Seconds
**              Interrupt request                          : Disabled
**              Interrupt priority                         : 0 (Highest)
**              ISR Name                                   : 
**              Seconds interrupt                          : Disabled
**          Initialization                                 : 
**            Time counter                                 : Disabled
**            Call Init method                             : yes
**     Contents    :
**         Init - void RTC_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file RTC.c
** @version 01.05
** @brief
**          This file implements the SRTC (RTC) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup RTC_module RTC module documentation
**  @{
*/         

/* MODULE RTC. */

#include "RTC.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  RTC_Init (component Init_SRTC)
**     Description :
**         This method initializes registers of the SRTC module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void RTC_Init(void)
{
  /* SIM_SCGC6: RTC=1 */
  SIM_SCGC6 |= SIM_SCGC6_RTC_MASK;
  /* RTC_SR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TCE=0,??=0,TAF=0,TOF=0,TIF=0 */
  RTC_SR = 0x00U;
  /* RTC_CR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,SC2P=1,SC4P=0,SC8P=1,SC16P=0,CLKO=0,OSCE=1,??=0,??=0,??=0,??=0,UM=0,SUP=0,WPE=0,SWR=0 */
  RTC_CR = (RTC_CR_SC2P_MASK | RTC_CR_SC8P_MASK | RTC_CR_OSCE_MASK);
  /* RTC_TPR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TPR=0 */
  RTC_TPR = RTC_TPR_TPR(0x00);
  /* RTC_TSR: TSR=0 */
  RTC_TSR = RTC_TSR_TSR(0x00);
  /* RTC_TAR: TAR=0 */
  RTC_TAR = RTC_TAR_TAR(0x00);
  /* RTC_TCR: CIC=0,TCV=0,CIR=0,TCR=0 */
  RTC_TCR = RTC_TCR_CIC(0x00) |
            RTC_TCR_TCV(0x00) |
            RTC_TCR_CIR(0x00) |
            RTC_TCR_TCR(0x00);
  /* RTC_IER: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TSIE=0,??=0,TAIE=1,TOIE=1,TIIE=1 */
  RTC_IER = (uint32_t)((RTC_IER & (uint32_t)~(uint32_t)(
             RTC_IER_TSIE_MASK |
             0xFFFFFF68U
            )) | (uint32_t)(
             RTC_IER_TAIE_MASK |
             RTC_IER_TOIE_MASK |
             RTC_IER_TIIE_MASK
            ));
  /* RTC_SR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TCE=0,??=0,TAF=0,TOF=0,TIF=0 */
  RTC_SR = 0x00U;
  /* RTC_LR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=1,LRL=1,SRL=1,CRL=1,TCL=1,??=1,??=1,??=1 */
  RTC_LR = RTC_LR_LRL_MASK |
           RTC_LR_SRL_MASK |
           RTC_LR_CRL_MASK |
           RTC_LR_TCL_MASK |
           0x87U;
}

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      main.c
**      Events.c
**
** ###################################################################
PE_ISR(RTCInterrrupt)
{
// NOTE: The routine should include actions to clear the appropriate
//       interrupt flags.
//
}
*/


/* END RTC. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
