/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : SSI1_TxDMA.c
**     Project     : TabataTimer4_2
**     Processor   : MKL26Z128VFT4
**     Component   : DMAChannel_LDD
**     Version     : Component 01.051, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-10-29, 09:04, # CodeGen: 0
**     Abstract    :
**          This embedded component implements
**          a DMA transfer channel descriptor definition.
**     Settings    :
**          Component name                                 : SSI1_TxDMA
**          Hardware request                               : Enabled
**            Request source                               : I2S0_Transmit_DMA_Request
**            Request periodic trigger                     : Disabled
**          Channel select                                 : Fixed
**            DMA controller device                        : DMA1
**            Channel                                      : DMA_Channel0
**            Allocate channel                             : yes
**            Arbitration type                             : Fixed
**              Priority                                   : 0
**            Interrupt service                            : Enabled
**              Transfer complete interrupt                : 
**                Interrupt vector                         : INT_DMA0
**                Interrupt priority                       : 2
**          External object declaration                    : (string list)
**          Source transaction settings                    : 
**            Start address                                : 
**            Transaction size                             : 16-bits
**            Address adjustment                           : 2
**            Address modulo                               : Buffer disabled
**          Destination transaction settings               : 
**            Start address                                : (LDD_DMA_TAddress)(I2S_PDD_GetTxDataRegAddress(I2S0_BASE_PTR))
**            Transaction size                             : 16-bits
**            Address adjustment                           : 0
**            Address modulo                               : Buffer disabled
**          Transfer settings                              : 
**            Auto-align mode                              : Disabled
**            Asynchronous requests                        : Disabled
**            Transaction size                             : 16-bits
**            Transactions count                           : 1
**            Request count                                : 1
**            After request complete actions               : 
**              Channel linking                            : Disabled
**              Address adjustment                         : Disabled
**            After transfer complete actions              : 
**              Disable peripheral request                 : yes
**              Channel linking                            : Disabled
**              Address adjustment                         : Disabled
**              Scatter/gather                             : Disabled
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : yes
**            Half complete                                : Disabled
**            Event mask                                   : 
**              OnComplete                                 : Enabled
**              OnError                                    : Enabled
**     Contents    :
**         Init                   - LDD_TDeviceData* SSI1_TxDMA_Init(LDD_TUserData *UserDataPtr);
**         Deinit                 - void SSI1_TxDMA_Deinit(LDD_TDeviceData *DeviceDataPtr);
**         EnableRequest          - LDD_TError SSI1_TxDMA_EnableRequest(LDD_TDeviceData *DeviceDataPtr);
**         DisableRequest         - LDD_TError SSI1_TxDMA_DisableRequest(LDD_TDeviceData *DeviceDataPtr);
**         CancelTransfer         - LDD_TError SSI1_TxDMA_CancelTransfer(LDD_TDeviceData *DeviceDataPtr);
**         GetTransferredDataSize - LDD_DMA_TTransferDataSize SSI1_TxDMA_GetTransferredDataSize(LDD_TDeviceData...
**         SetSourceAddress       - LDD_TError SSI1_TxDMA_SetSourceAddress(LDD_TDeviceData *DeviceDataPtr,...
**         SetRequestCount        - LDD_TError SSI1_TxDMA_SetRequestCount(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SSI1_TxDMA.c
** @version 01.00
** @brief
**          This embedded component implements
**          a DMA transfer channel descriptor definition.
*/         
/*!
**  @addtogroup SSI1_TxDMA_module SSI1_TxDMA module documentation
**  @{
*/         

/* MODULE SSI1_TxDMA. */

#include "SSI1.h"
#include "SSI1_TxDMA.h"
#include "FreeRTOS.h" /* FreeRTOS interface */

#define SSI1_TxDMA_INIT_EVENTS_MASK ((LDD_TEventMask)( \
          LDD_DMA_ON_COMPLETE | \
          LDD_DMA_ON_ERROR))

/* Channel configuration structure */
DMA1_TChnInit const SSI1_TxDMA_ChInit = {
  /* Logical channel number */
  DMA1_STATIC_CHANNEL_3,               /* Phy channel: DMA_Channel0 */
  { /* TCD initial settings */
    DMA_SAR_SAR(0x00),                 /* SAR register initial value */
    DMA_DAR_DAR(0x00),                 /* Initial value is not constant expresion. See Init() method to see initial value. */
    DMA_DSR_BCR_BCR(0x02),             /* DSR_BCR register initial value */
    ( DMA_DCR_EINT_MASK |
      DMA_DCR_CS_MASK |
      DMA_DCR_SINC_MASK |
      DMA_DCR_SSIZE(0x02) |
      DMA_DCR_DSIZE(0x02) |
      DMA_DCR_SMOD(0x00) |
      DMA_DCR_DMOD(0x00) |
      DMA_DCR_D_REQ_MASK |
      DMA_DCR_LINKCC(0x00) |
      DMA_DCR_LCH1(0x00) |
      DMA_DCR_LCH2(0x00)
    )                                  /* DCR register initial value */
  },
  /* DMAMUX initial settings */
  (DMAMUX_CHCFG_ENBL_MASK | DMAMUX_CHCFG_SOURCE(0x0F)), /* DMA multiplexor configuration register initial value 'I2S0_Transmit_DMA_Request' */
  { /* Events initial setting */
    &SSI1_TxDMA_OnComplete,            /* OnComplete callback address */
    &SSI1_TxDMA_OnError                /* OnComplete callback address */
  }
};

/*
** ===================================================================
**     Method      :  SSI1_TxDMA_Init (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Initializes the DMAChannel_LDD component. This method
**         allocates no memory. Memory for all DMA used channles is
**         allocated by DMAController componet .
**         This method can be called only once. Before the second call
**         of Init() the Deinit() must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Device data structure pointer.
*/
/* ===================================================================*/
LDD_TDeviceData* SSI1_TxDMA_Init(LDD_TUserData *UserDataPtr)
{
  LDD_TDeviceData                 *DevDataPtr; /* DMA device data structure pointer */
  LDD_TDeviceData                 *ChnDevDataPtr; /* DMA channel device data structure pointer */
  DMA1_TChnInit                    ChnInit;

  DevDataPtr = PE_LDD_DeviceDataList[PE_LDD_COMPONENT_DMA1_ID]; /* Get DMA peripheral handle */
  if (DevDataPtr == NULL) {            /* Is DMA peripheral initialized? */
    DevDataPtr = DMA1_Init();          /* No, try to initialize it */
    if (DevDataPtr == NULL) {          /* initialization failed? */
      return NULL;                     /* Yes, return NULL */
    }
  }
  ChnInit = SSI1_TxDMA_ChInit;         /* Initialize local copy of init. structure */
  ChnInit.TCD.DMA_DAR_Reg = 
DMA_DAR_DAR((LDD_DMA_TAddress)(I2S_PDD_GetTxDataRegAddress(I2S0_BASE_PTR))); /* DAR register initial value */
  /* Initialize DMA channel device and get DMA channel handle */
  ChnDevDataPtr = DMA1_InitChannel(DevDataPtr, (DMA1_TChnInit *)(void *)&ChnInit, UserDataPtr);
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_SSI1_TxDMA_ID,ChnDevDataPtr);
  /* Return pointer to the channel data structure */
  return (ChnDevDataPtr);
}

/*
** ===================================================================
**     Method      :  SSI1_TxDMA_Deinit (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Deinitializes the DMAChannel_LDD component.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
*/
/* ===================================================================*/
void SSI1_TxDMA_Deinit(LDD_TDeviceData *DeviceDataPtr)
{
  (void)DMA1_DeinitChannel((DMA1_TChanDeviceData *)DeviceDataPtr);
  /* Unregistration of the device structure */
  PE_LDD_UnregisterDeviceStructure(PE_LDD_COMPONENT_SSI1_TxDMA_ID);
}

/*
** ===================================================================
**     Method      :  SSI1_TxDMA_EnableRequest (component DMAChannel_LDD)
*/
/*!
**     @brief
**         The method enables request from peripheral. Please note that
**         this method doesn't start the transfer. The transfer is
**         started as soon as DMA request from peripheral is asserted.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled.
*/
/* ===================================================================*/
LDD_TError SSI1_TxDMA_EnableRequest(LDD_TDeviceData *DeviceDataPtr)
{
  return DMA1_EnableRequest((DMA1_TChanDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  SSI1_TxDMA_DisableRequest (component DMAChannel_LDD)
*/
/*!
**     @brief
**         The method disables DMA request from peripheral. Request can
**         also by disabled automatically by the DMA hardware if
**         "[Disable request after transfer done]" property is set to
**         "yes" value.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled.
*/
/* ===================================================================*/
LDD_TError SSI1_TxDMA_DisableRequest(LDD_TDeviceData *DeviceDataPtr)
{
  return DMA1_DisableRequest((DMA1_TChanDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  SSI1_TxDMA_CancelTransfer (component DMAChannel_LDD)
*/
/*!
**     @brief
**         This method cancels DMA transfer. The cancel takes effect
**         after the last write of the current read/write sequence and
**         the channel retires as if the request was serviced normally.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled.
*/
/* ===================================================================*/
LDD_TError SSI1_TxDMA_CancelTransfer(LDD_TDeviceData *DeviceDataPtr)
{
  return DMA1_CancelTransfer((DMA1_TChanDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  SSI1_TxDMA_GetTransferredDataSize (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Returns current number of transferred transaction units.
**         Returned value reflects either number of transaction units
**         transferred in the currently active transfer or number of
**         transaction units transferred the in last completed transfer.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Number of transferred transaction units.
*/
/* ===================================================================*/
LDD_DMA_TTransferDataSize SSI1_TxDMA_GetTransferredDataSize(LDD_TDeviceData *DeviceDataPtr)
{
  return DMA1_GetTransferredDataSize((DMA1_TChanDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  SSI1_TxDMA_SetSourceAddress (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Sets source(read) transaction address.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Address         - Data source address.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled. 
**                           - ERR_PARAM_ADDRESS - Source address is not
**                           multiple of DMA transaction size (byte,
**                           word, dword, ...)
*/
/* ===================================================================*/
LDD_TError SSI1_TxDMA_SetSourceAddress(LDD_TDeviceData *DeviceDataPtr, LDD_DMA_TData *Address)
{
  return DMA1_SetSourceAddress((DMA1_TChanDeviceData *)DeviceDataPtr, Address);
}

/*
** ===================================================================
**     Method      :  SSI1_TxDMA_SetRequestCount (component DMAChannel_LDD)
*/
/*!
**     @brief
**         Sets number of requests required to complete transfer.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         RequestCount    - Number of requests
**                           required to complete transfer.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK. 
**                           - ERR_DISABLED - Component is disabled.
*/
/* ===================================================================*/
LDD_TError SSI1_TxDMA_SetRequestCount(LDD_TDeviceData *DeviceDataPtr, LDD_DMA_TRequestCount RequestCount)
{
  return DMA1_SetRequestCount((DMA1_TChanDeviceData *)DeviceDataPtr, RequestCount);
}

/* END SSI1_TxDMA. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
